### ISSUE TITLE
Pext is not working in Arch Linux installed from AUR.

### ISSUE THREAD

**Issue by airvzxf** [Pext/Pext#475] opened 2022-10-16 20:44 UTC
**Describe the bug**
I installed `pext` from the AUR repository in Arch Linux, but every time I executed, it shows an error in console and crash.
```
/home/wolf/.local/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.10) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/pext", line 33, in <module>
    sys.exit(load_entry_point('Pext==0.32', 'gui_scripts', 'pext')())
TypeError: main() missing 1 required positional argument: 'ui_type'
```

**To Reproduce**
1. Open a terminal.
1. `yay -S pext`
2. execute `pext` or `pext --version`

**Expected behavior**
Open the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/831380/196057656-1fad2ed7-8061-40d9-a80d-724ffa34a8d0.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux: Linux 6.0.1-arch2-1 # 1 SMP PREEMPT_DYNAMIC Thu, 13 Oct 2022 18:58:49 +0000 x86_64 GNU/Linux
 - Pext version [check About screen or run Pext with --version]: N/A
 - Module version (if applicable) [Module -> manage modules -> Version]: N/A
 - Python version: Python 3.10.8

**Quick Note:**
Could you add the labels "hacktoberfest and hacktoberfest-accept" to this issue?

**Additional context**
```
                   -`
                  .o+`                 wolf@MSIGT73EVR7RF
                 `ooo/                 OS: Arch Linux
                `+oooo:                Kernel: x86_64 Linux 6.0.1-arch2-1
               `+oooooo:               Uptime: 5h 3m
               -+oooooo+:              Packages: 1600
             `/:-:++oooo+:             Shell: zsh 5.9
            `/++++/+++++++:            Resolution: 3840x1080
           `/++++++++++++++:           WM: OpenBox
          `/+++ooooooooooooo/`         WM Theme: Clearlooks
         ./ooosssso++osssssso+`        GTK Theme: Adwaita [GTK3]
        .oossssso-````/ossssss+`       Disk: 353G / 469G (79%)
       -osssssso.      :ssssssso.      CPU: Intel Core i7-7820HK @ 8x 3.9GHz [51.0°C]
      :osssssss/        osssso+++.     GPU: NVIDIA GeForce GTX 1080
     /ossssssss/        +ssssooo/-     RAM: 5247MiB / 64269MiB
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
```

**Comment by TheLastProject** [comment] 2022-10-17 17:21
I believe this is a semi-duplicate of #382.

I really want to do a new release but given the AppImage (#470) and macOS (#471) builds are currently broken I can't really do that as I can't generate all the release files :(

**Comment by TheLastProject** [comment] 2022-11-07 22:46
Did you ever get the git version working? I should do a new release now all the builds are good (thank you so much for that) but I wonder if all the brokenness launching is fixed now

**Comment by airvzxf** [comment] 2022-11-10 03:32
I tried during the last pull request, but it was returning the same error. We can work together to fix it. But, I think is better, as you mentioned, that did the new releases and check if it solves the problem in Arch Linux for the AUR version.

**Comment by TheLastProject** [comment] 2022-12-07 21:00
Seems it's still broken :/
```
Using locale: en_US (system locale)
Localization loaded: False
Traceback (most recent call last):
  File "/usr/bin/pext", line 33, in <module>
    sys.exit(load_entry_point('Pext==0.34', 'gui_scripts', 'pext')())
  File "/usr/lib/python3.10/site-packages/pext/__main__.py", line 3313, in run_qt5
    main(UIType.Qt5)
  File "/usr/lib/python3.10/site-packages/pext/__main__.py", line 3261, in main
    from ui_qt5 import Window, Tray, HotkeyHandler, SignalHandler
  File "/usr/lib/python3.10/site-packages/pext/ui_qt5.py", line 50, in <module>
    from main import (AppFile, ConfigRetriever, Core, InternalCallProcessor, LocaleManager, Logger, ModuleManager,
ImportError: cannot import name 'AppFile' from '__main__' (/usr/bin/pext)
```

**Comment by TheLastProject** [comment] 2022-12-07 21:54
Should be fixed in f9a0c051fa5d7116ec4e8db6cd8a3e388b108717

**Closed** 2022-12-08 14:13 UTC

**Comment by airvzxf** [comment] 2022-12-08 15:51
Confirmed, it is working.
![Screenshot_2022-12-08_09-49-06](https://user-images.githubusercontent.com/831380/206493801-4ce47049-b3a9-4f7b-a1bd-52c9cd0370a8.png)

**Comment by airvzxf** [comment] 2022-12-08 15:55
It is working fine. I ran `yay -S pext`, and it is the result:

![Screenshot_2022-12-08_09-54-50](https://user-images.githubusercontent.com/831380/206495329-99b816e9-e89a-4304-8bbe-75931057d256.png)

**Comment by TheLastProject** [comment] 2022-12-08 17:38
Thanks for confirming :)
